baseURL = 'https://summerrainnn.github.io/blog-hugo/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "m10c"

[params]
  author = "summerrainnn"
  description = "A blogl."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/summerrainnn"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/"